ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS project_types TEXT[] DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS pending_blocks TEXT[] DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS current_block TEXT NULL;
